services:
  flask:
    image: jankrom1/voice-vault-flask:${MODEL_TAG_DOCKER}
    ports:
      - "80:6000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL=${MODEL}
      - PASSWORD=${PASSWORD}
    networks:
      - ai-network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    image: jankrom1/voice-vault-ollama:${MODEL_TAG_DOCKER}
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama/models
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - MODEL=${MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  ollama-models:
    driver: local
